/** @format */
import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Andrew",
      email: "andrew@gmail.com",
      password: bcrypt.hashSync("andrew123"),
      isAdmin: true,
    },
    {
      name: "Trevor",
      email: "trevor@gmail.com",
      password: bcrypt.hashSync("trevor123"),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "SEPULTURA 33 RPM 12 inch - Beneath The Remains 2LP ORANGE & YELLOW VINYL LMTD SEALED",

      slug: "beneaththeremains",
      category: "Vinyl",
      image: "/images/s-l1600.png",
      price: 40,
      brand: "Korn",
      countInStock: 1,
      description: "1500 copies made!",
    }, {
      name: "Korn Featuring Skrillex, Kill The Noise – Narcissistic Cannibal",
      slug: "Narckorneu",
      category: "promo CD",
      image: "/images/Kornnarc.png",
      img2: "/images/Kornnarc1.png",
      img3: "/images/Kornnarc3.png",
      price: 13,
      brand: "Korn",
      countInStock: 1,
      description: "European 1 track CD single in cardsleeve case",
    },
    {
      name: "Korn - Narcissistic Cannibal - DANISH PrOMO CD",
      slug: "narckorndanish",
      category: "promo CD",
      image: "/images/kornnarcdansk.jpg",
      price: 40,
      brand: "Korn",
      countInStock: 1,
      description: "Uber rare Dansk 10 track remix promo CD in plastic sleeve",
    },
    {
      name: "Korn - Get Up! - Dansk Promo",
      slug: "korngetupdanish",
      category: "promo CD",
      image: "/images/korn_getup_dasnk.png",
      price: 40,
      brand: "Korn",
      countInStock: 1,
      description: "Uber rare Dansk  promo CD in plastic sleeve",
    },

    {
      name: "Requiem LP (coke bottle clear)",
      slug: "kornrequiemcokebottleclear",
      category: "vinyl",
      image: "/images/requiemlpcokebottleclear.jpg",
      price: 40.0,
      brand: "Korn",
      countInStock: 1,
      description: "Out of print Wallmart exclusive color way. Mint & Sealed",
    },
    {
      name: "Requiem LP (Revolver Exclusive silver colorway)",
      slug: "Reqsilver",
      category: "vinyl",
      image: "/images/kornreqsilver copy.jpg",
      price: 50.0,
      brand: "Korn",
      countInStock: 1,
      description:
        "Revolver exclusive silver color way. Mint & Sealed - 1000 copies made",
    },
    {
      name: "Creep 1-track promo CD",
      slug: "korncreep1track",
      category: "CDr Advance promo",
      image: "/images/korn_creep_1track_promo_cd.jpg",
      price: 50.0,
      brand: "Korn",
      countInStock: 1,
      description:
       "Rare Virgin Records advance promo of the acoustic rendition taken from MTV Unplugged",
    },
    {
      name: "Family Forum",
      slug: "family-forum-cd",
      category: "live CD ",
      image: "/images/FamilyForum.png",
      img2: "/images/familyforumdisc.png",
      img3: "/images/familyforumback.png",
      price: 25,
      brand: "Korn",
      rating: 4.2,
      numReviews: 10,
      countInStock: 1,
      description:
        "Tracks 1-8 L.A. Shrine Auditorium 12-11-98, Tracks 9-16 Live at The Forum 1998",
      isFeatured: true,
      banner: "/images/IMG_5796.jpg",
    },
    {
      name: "Korn - Freak On a Leash (REMIX)",
      slug: "korn-FOAL-Dante",
      category: "Promo CD",
      image: "/images/kornfreakdante-1.JPG",
      price: 20.0,
      brand: "Korn",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description:
        "Rare 1 track remix cd for Freak On A Leash (Dante Ross Remix). Item released with no front or back insert",
    },
    {
      name: "Korn - 2 track cassette, 1994",
      slug: "korn-blind-clown",
      category: "promo cassette",
      image: "/images/korn1994front-1.jpg",
      img2: "/images/korn1994back-1.jpg",
      price: 100,
      brand: "Korn",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description: "Rare 2 track promo cassette taken from the 1994 debut self titled Album",
    },

    {
      name: "Korn - Live At the Palace",
      slug: "korn-live-at-palace",
      category: "live cd",
      image: "/images/kornliveatpalace-1.JPG",
      img2: "/images/kornpalace1995back.png",
      img3: "/images/blackonsilver.jpeg",
      img3: "/images/blackonsilver.jpeg",
      price: 25,
      brand: "KORN",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description: "A popular promo cd",
    },
    {
      name: "Korn - Wicked & Twisted",
      slug: "korn-wick-twist",
      category: "live cd",
      image: "/images/korn_wicked_twisted.png",
      img2: "/images/wickedandtwistedback-1.JPG",
      img3: "/images/blackonsilver.jpeg",
      img3: "/images/blackonsilver.jpeg",
      price: 40,
      brand: "KORN",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description: "A popular promo cd",
    },
    {
      name: "DEFTONES OHMS Cassette Bundle!",
      slug: "OHMSbundle",
      category: "Limited Edition cassette bundle",
      image: "/images/deftones_ohms_casette_bundle.jpg",

      price: 150,
      brand: "Deftones",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description:
        "Limited Edition Green, silver & pink Cassette variants (300 copies made per color) ",
    },
    {
      name: "Family Values Tour 1998 cassette tape",
      slug: "FamilyValues98cassette",
      category: "music cassette",
      image: "/images/FV98 cassette.png",
      price: 35,
      brand: "Family Values Tour 1998",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description: "Family Values 1998 full length cassette (SEALED!)",
    },
    {
      name: "KORNSTAR",
      slug: "KORNSTAR",
      category: "music",
      image: "/images/KORNSTAR.jpeg",
      img2: "/images/KORNSTARBACK.png",

      price: 30,
      brand: "KORN",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
      description: "LIVE CDr, UNOFFICIAL RELEASE",
    },
    {
      name: "Requiem 'silver'version cassette ",
      slug: "korn-requiem-cassette-silver",
      category: "music",
      image: "/images/kornrequiemcas_1024x.webp",
      img2: "/images/requeim_silver-2.jpg",
      img3: "/images/requeim_silver-1.jpg",
      img4: "/images/requeim_silver-3.jpg",
      price: 75,
      brand: "Deftones",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "Limited Edition Metallic Shell Cassette (Edition of 300 units worldwide)",
    },
  ],
};

export default data;
